### ISSUE TITLE
correct_pad

### ISSUE THREAD

**Issue by jeranio** [songhengyang/face_landmark_factory#13]
In mobile_net_v2.py line 83 "from . import correct_pad" , where is this file? Thanks

**Comment by jeranio** [comment]
Never mind found it. Thanks

**Comment by soans1994** [comment]
@jeranio 

hello, the author is probably dead. how did you fix this issue?

thank you

**Comment by jeranio** [comment]
Check here /face_landmark_factory/net /__init__.py/
I am inside a virtual environment and this is part of my paths

**Comment by soans1994** [comment]
thank you
